version: "3.4"

services:
  app:
    build: 
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - storage
      - db
      - cache
    environment:
      - STORAGE_ADDR
      - STORAGE_USER
      - STORAGE_PASS
      - STORAGE_NAME

      - DB_ADDR
      - DB_USER
      - DB_PASS
      - DB_NAME

      - CACHE_ADDR
      - CACHE_USER
      - CACHE_PASS
      - CACHE_DB

      - FILE_CACHE_ADDR
      - FILE_CACHE_USER
      - FILE_CACHE_PASS
      - FILE_CACHE_DB

      - APP_ADDR
      - APP_ID_LENGTH
      - APP_MAX_SIZE
      - APP_TIMEOUT_READ
      - APP_TIMEOUT_WRITE
      - APP_LOG_LEVEL
      - APP_PUBLIC_PATH
      - APP_MAX_FILE_MEMORY
      - APP_DEFAULT_EXPIRATION

      - LOCKER_ADDR
      - LOCKER_USER
      - LOCKER_PASS
      - LOCKER_DB

  cache:
    image: redis:7.2.3-bookworm
    volumes:
      - ./_cache_data:/data

  storage:
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z-cpuv1
    command: server /data
    environment:
      MINIO_ROOT_USER: $STORAGE_USER
      MINIO_ROOT_PASSWORD: $STORAGE_PASS
    volumes:
      - ./_data:/data
      - ./_minio_config:/root/.minio

  db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./_db_data:/var/lib/postgresql/data

